### ISSUE TITLE
Unable to upload firmware to OpenLog modules

### ISSUE THREAD

**Issue by TimSRT** [sparkfun/OpenLog#143]
I successfully loaded v3.14 onto a board that had previously had v2.5 on it but when I tried to do the same thing with three other boards that look the same/genuine (but came with v3.11 installed) the bootloader doesn't seem to be working - the command window extract below shows the successful operation (on the older board) and then two unsuccessful attempts with the other boards.  I am using the "apply power then hit return key" method.  If I leave it too long the response is "avrdude.exe: stk500_getsync(): not in sync: resp=0x00"

<begin>
C:\Users\Timl\Documents\AVR\OpenLog>avrdude.exe -p atmega328p -P COM5 -c stk500v
1 -b 57600 -Cavrdude.conf -U flash:w:main.hex

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude.exe: Device signature = 0x1e950f
avrdude.exe: NOTE: FLASH memory has been specified, an erase cycle will be perfo
rmed
             To disable this feature, specify the -D option.
avrdude.exe: erasing chip
avrdude.exe: reading input file "main.hex"
avrdude.exe: input file main.hex auto detected as Intel Hex
avrdude.exe: writing flash (29354 bytes):

Writing | ################################################## | 100% 14.66s

avrdude.exe: 29354 bytes of flash written
avrdude.exe: verifying flash memory against main.hex:
avrdude.exe: load data flash data from input file main.hex:
avrdude.exe: input file main.hex auto detected as Intel Hex
avrdude.exe: input file main.hex contains 29354 bytes
avrdude.exe: reading on-chip flash data:

Reading | ################################################## | 100% 12.36s

avrdude.exe: verifying ...
avrdude.exe: 29354 bytes of flash verified

avrdude.exe: safemode: Fuses OK

avrdude.exe done.  Thank you.

C:\Users\Timl\Documents\AVR\OpenLog>avrdude.exe -p atmega328p -P COM5 -c stk500v
1 -b 57600 -Cavrdude.conf -U flash:w:main.hex
avrdude.exe: stk500_getsync(): not in sync: resp=0x31
avrdude.exe: stk500_disable(): protocol error, expect=0x14, resp=0x51

avrdude.exe done.  Thank you.

C:\Users\Timl\Documents\AVR\OpenLog>avrdude.exe -p atmega328p -P COM5 -c stk500v
1 -b 57600 -Cavrdude.conf -U flash:w:main.hex
avrdude.exe: stk500_getsync(): not in sync: resp=0x65
avrdude.exe: stk500_disable(): protocol error, expect=0x14, resp=0x51

avrdude.exe done.  Thank you.

C:\Users\Timl\Documents\AVR\OpenLog>
<end>

**Comment by SteveCEvans** [comment]
I had a similar issue, fixed by running avrdude at 115200 baud. Looks like the bootloader is now running at 115200 rather than 57600 by default.
