### ISSUE TITLE
Openlog -- example of reading/counting chars in a file - decimal character display

### ISSUE THREAD

**Issue by BuddyAid** [sparkfun/OpenLog#177]
Hi,

I have encountered a strange issue.  I am running the test code for reading/counting chars in a file.  I am using this "smltext.txt" file for testing purposes.  Decimal numbers are being displayed on Hyper Terminal as the characters, instead of ASCII characters.  Does anyone know why this is the case?

Extract from Hyper terminal:

File read complete
Bluetooth connection online
13104950515253131062
Characters read: 10

13,10,49,50,51,52,53,13,10,62 .. see my description below:

Decimal 13 being carriage return, 10 - being line feed, 49 to 53 - 1,2,3,4,5, and then again carriage return and line feed, and then decimal 62, which is ">"

Thanks

**Comment by nseidle** [comment]
Sorry for not getting to this issue sooner. 

I'm slightly confused and presume you have posted the contents of your log "smltext.txt" that was picked up by OpenLog.

You have some other devices at play (a bluetooth connection). If I had to guess the bluetooth module is reporting status messages in ASCII but is dumping the incoming characters in a weird way.

OpenLog will record exactly what it is presented with. In this case, if your bluetooth module is sending "131049...." that's what OpenLog will log.

Please re-open if you have other questions.
