### ISSUE TITLE
Eagle Cad file error

### ISSUE THREAD

**Issue by rconry60** [sparkfun/OpenLog#180]
From the hardware section, right clicked on the .sch and .brd files and selected "save link as...", saved the files locally.  Attempted to open (in Eagle v6.1 and v7.2) but was given the message 
"Error:
line 6, column 25: This is not an EAGLE file."

I have seen closed issues where the files could be corrupted because the raw file is being downloaded but that is not the case.

**Comment by nseidle** [comment]
Hello! Github is not friendly when it comes to downloading a single file or two. Right clicking and save as will not work. You have to click on the file, then raw. This should cause your browser to download the file.

If that doesn't work, goto the main page: https://github.com/sparkfun/OpenLog and click on 'Download As Zip' button on the right side. You'll get all the files that you don't need but you'll also get the true brd and sch files.

Cheers,
-Nathan
