### ISSUE TITLE
No/wrong serial communication

### ISSUE THREAD

**Issue by Brodi** [sparkfun/OpenLog#182]
We have been able to log data over the arduino with this board, however when I try communicate over serial directly (putty, teraterm) I don't get the 12> on start up.  It outputs g3 usually, so I know the com1 port is correct and I'm using 9600 8N1 BAUD. The CONFIG.TXT file is the standard 9600,26,0,1,1,0 .  Also I can't access the commands (Ctrl+z).

Thank you.

**Comment by Brodi** [comment]
Just realised that my USB converter is RS-232, not TTL.  My Dumb.  I'll use a converter and report back.

**Comment by Brodi** [comment]
Yup.  Problem resolved.

**Comment by nseidle** [comment]
Best issue resolution ever. Thanks for coming back to post+close it!

**Comment by Brodi** [comment]
Well, I hate leaving people in suspense.
