### ISSUE TITLE
LED not working on stm32

### ISSUE THREAD

**Issue by puedpued** [sparkfun/OpenLog#191]
The openlog works fine with arduino, the blue LED is ON when data is being transmitted.
When I use it with an STM32F411 microcontroller, the data transmits normally but the blue LED is not lit to show when it's communicating with the microcontroller.

Am I missing something? Is there a way to fix this?

Thank you in advance.

**Comment by nseidle** [comment]
Hmm. Do you have the ability to check the communication with a logic analyzer? Do you know what voltage the STM is communicating at?

**Comment by thenickdude** [comment]
To clarify, are you saying that the data is logged fine but the blue LED doesn't light up?

**Comment by puedpued** [comment]
I know what the problem was. I had the transmitting rate too slow, hence, causing the led to hardly flash and my room was too bright to actually realize it was flashing. Once I increased the trandmitting rate it all works fine :)
