### ISSUE TITLE
Spec Update

### ISSUE THREAD

**Issue by BrentWilkins** [sparkfun/OpenLog#193]
The product page reads that "OpenLog currently supports FAT16 and FAT32 microSD cards (we’ve tested up to 64GB!)", while the README here reads only 2GB.  Are they both true?

**Comment by bhuang10000** [comment]
I've tested it with 8 GB cards -- the ones that are at SparkFun. I think the 2 GB is a remnant from an old spec.

**Comment by nseidle** [comment]
Not sure where you saw 2GB as the spec (that was version 1, a long time ago). But I updated the readme to make it more clear.
