### ISSUE TITLE
v15 hardware review [for reds]

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/OpenLog#202]
1) Does it pass SparkFun DRC? [NO]
comment: Not sure how I missed this on the checklist for proto, but there's an overlap error - a GND via sitting on the upper left pad of the SD socket, I'd like to see that via moved off that pad to prevent sucking away the paste

2) If there are any DRC errors, have they all been approved? [NO]
comment: a couple dimension errors should be approved

**Comment by nseidle** [comment]
Cool. Via removed/fixed in branch v15: https://github.com/sparkfun/OpenLog/tree/hardware-v15
