### ISSUE TITLE
Storing data in flash

### ISSUE THREAD

**Issue by BrentWilkins** [sparkfun/OpenLog#204]
The prog_char typedef is depreciated. Please change from the 'const prog_char' format to the 'char PROGMEM' format.

**Comment by nseidle** [comment]
Good catch. This is fixed by pulling the most recent version of SerialPort.cpp and h from Bill's repo: https://github.com/greiman/SerialPort/tree/master/SerialPort I've also made a copy and pushed it in the main OpenLog repo.
