### ISSUE TITLE
if (setting_echo != ON || setting_echo != OFF)

### ISSUE THREAD

**Issue by jys0305** [sparkfun/OpenLog#208]
in this function void readSystemSettings(void)，
 setting_verbose = EEPROM.read(LOCATION_VERBOSE);
if (setting_verbose != ON || setting_verbose != OFF)
  {
    setting_verbose = ON; //Reset verbose to true
    EEPROM.write(LOCATION_VERBOSE, setting_verbose);
  }
as result ,setting_verbose will always be ON,.i think here should be if (setting_verbose != ON && setting_verbose != OFF)

**Comment by nseidle** [comment]
You are absolutely correct. Thank you. I will fix this on the next commit.

**Comment by nseidle** [comment]
Fixed in latest commit. Thanks again!
