### ISSUE TITLE
unresponsive OpenLog device, blue LED blinking 3x...

### ISSUE THREAD

**Issue by RootlessAgrarian** [sparkfun/OpenLog#209]
I am not that experienced yet with Arduino (have worked my way through all examples in the Uno beginner book successfully).  This is my first non-Genuino part (Sparkfun OpenLog board).

So I soldered header pins onto the board, and wired it up to my Uno per this guide 

http://arduino.stackexchange.com/questions/30389/where-on-uno-to-connect-blk-and-grn-pins-of-openlog-board

I then attempted to load the sketch OpenLog_CommandTest, which I DL'd from Sparkfun's web site.  This seemed to be the basic "Hello World" test for this device.

I am able to upload the sketch only if I pull the tx and rx wires, otherwise I get the dreaded avrdude error.  I posted about this error originally.   I have added a 5 sec delay into the example sketch to give me time to reinsert the wires before the sketch attempts to contact the OpenLog device:
 
```
//Reset OpenLog
  digitalWrite(resetOpenLog, LOW);
  delay(100);
  digitalWrite(resetOpenLog, HIGH);
  
  signal(1);
  delay(5000);  // plug in tx rx  wires now!
  signal(1);
```

('signal' is a void func of my own which blinks the Uno built-in LED with distinctive patterns, giving me a low level debug capability).
  
```
//Wait for OpenLog to respond with '<' to indicate it is alive and recording to a file
  while(1) {
    if(Serial.available())
      signal(2);
      if(Serial.read() == '<') break;
  }

```

We get the first signal (4 slow blinks), and after 5 seconds during which I plug the tx and rx wires in again, we get the second signal (4 slow blinks).  But then... no more blinks.  I conclude that Serial.available() never becomes true, and so we are stuck forever in that while loop.  I don't know why Serial.available() would never become true.

It bears repeating that I am not that experienced with Arduino.  I bought this OpenLog device because it sounded like it "just works out of the box" for logging data from an Arduino project.  I am therefore pretty much flummoxed when the demo sketch doesn't work as described;  out of my depth already.  I don't know what I should try next.  I did notice that there's no "include" macro at the top of the demo sketch;  I expected that there would be an include of some OpenLog library.  Could this be my issue?

(UPDATE) I tried the OpenLogReadExample sketch.  Once again, all my OL will do is blink its blue LED three times.  This apparently indicates a problem with the SD card;  however, this SD card formats OK as FAT (under OSX using Disk Utility), and I can put a config.txt file on it.  It mounts and unmounts under OSX without issue.  So I don't know why OL would blink at it.  Did I just get a dud unit?

**Comment by nseidle** [comment]
I have re-written the example files. Please see them [here](https://github.com/sparkfun/OpenLog/tree/master/firmware/Arduino_Examples). Example1 should help you get started.

I recommend you use SoftwareSerial and avoid using the hardware serial port. Every time you upload a new sketch it can lead to accidental re-configuring of your OpenLog.
