### ISSUE TITLE
How to read the file number from eeprom and reset it from config.txt ?

### ISSUE THREAD

**Issue by sorenoneill** [sparkfun/OpenLog#222]
### Subject of the issue

Two simple(?) questions:
a) is it possible to read the auto-inc number of the current file? (I would like to present this on a digit display to the user)
b) Is it possible to reset the auto-inc number via the config file?

### Your workbench
* Arduino Uno
* BN: Arduino/Genuino Uno
* VID: 2341
* PID: 0043
* SN: 55731323935351C011A1
* Breadboard for now -- soldered soon
* Via Arduino

**Comment by nseidle** [comment]
Hi - sorry for the slow reply.

a) Currently we do not have a way to read the auto-increment log number via command. However, you can use the [ls command](https://learn.sparkfun.com/tutorials/openlog-hookup-guide#command-set) to list the files and identify the last file number.

b) Good question, I'm sorry but currently we don't offer that option. I never thought someone would need to reset the log number via the config file. I really don't want to add another variable to the config file (it's already getting a bit large) so for now I'll create a feature request/issue for it.
