### ISSUE TITLE
Openlog LS command question

### ISSUE THREAD

**Issue by danistrigaro** [sparkfun/OpenLog#231]
Dear all,

I am using OpenLog as datalogger to store environmental data. I do not understand which is the order of the files returned by the 'ls' command. At the beginning I thought that it was by alphabetic order, then I thought it was by creation time, but now I noticed that still is not like this.

Could you please give me some information about it?

Thank you very much in advance

Regards

Daniele

**Comment by nseidle** [comment]
OpenLog is based on [SdFat](https://github.com/greiman/SdFat) written by Bill Greiman and inherits its ls command. The ls function is defined in the docs as:

![image](https://user-images.githubusercontent.com/117102/56046664-feef7580-5d00-11e9-8a0e-50c9309f8e42.png)

ls function is defined [here](https://github.com/greiman/SdFat/blob/master/src/FatLib/FatFilePrint.cpp#L99). It is not apparent to me what the listing format is. It may be something lower level such as the order in which the files were written to the SD card.

**Comment by loricrotser** [comment]
Daniele, did you need further help with this issue? If you do, please feel free to look into our [forums](https://forum.sparkfun.com/index.php) - we have tech support folks who can get you going in the right direction. Thank you!
