### ISSUE TITLE
Continuous binary logging data loss

### ISSUE THREAD

**Issue by greydet** [sparkfun/OpenLog#62]
I got my device sending a continuous flow of binary data to the OpenLog in new file mode. I encounter data loss issues once the UART speed is greater than 9600bps.
The OpenLog datasheet says that such data loss only occur at 57600bps and higher.

Following are the loss rates I observe in function of the uart speed :
- 9600bps: 0%
- 19200bps: 0.97%
- 38400bps: 34.33%
- 57600bps: 43.50%
- 115200bps: 64.45%

Those stats are captured from a continuous write to the UART during approximately 30s.

My OpenLog firmware version is 2.41.
The device that sends data to the OpenLog is a custom board based on a Microchip dsPic33FJ128MC802. The OpenLog is powered at 5V.

**Comment by thomasylo** [comment]
At 115200 baud use SD card with write speed of 40 MByte per second for continouous logging.  Noname brand card barely works for 9600.  They usually do not even specify the write rate.  I found Samsung's 16GB card with the above speed good enough.  They also have 32GB card that runs at 80Mbyte per second in write.
