### ISSUE TITLE
Multiple files created

### ISSUE THREAD

**Issue by JustinWhitaker** [sparkfun/OpenLog#81]
I get multiple files on my SD card after running the OpenLog_Test_Sketch.  I have loaded the v2.51 firmware onto the OpenLog to be sure that is up to date, and I have run the test sketch from an arduino mega 2560 and an arduino pro mini 328 5V, and get the same results with both combinations.  I'm using the 9600bps and the testAmt = 4 settings in the sketch and this last time I got 48 files with all the test data.  The OpenLog and the SD card are from Sparkfun, just purchased last week.  It's a 1GB SD card that I formatted with SDFormatter V3.1 downloaded from sdcard.org, using the default settings.

I did see one other closed issue with a similar problem in which reloading the firmware solved the problem, but that didn't seem to help me.  Any suggestions?

Thanks in advance,
Justin

**Comment by Yury-MonZon** [comment]
I'm having the same problem. Using latest minimal build (no config file) and 57600. Electronic-wise everything is correct. Sometimes I get one big file and many small ones with the same size (3 735 bytes), sometimes many small files with random sizes and/not a big one.

I'm sending the string with \r\n in it, could that be the case?

**Comment by DudeYarvie** [comment]
Has a definitive solution been found for these issues?  I just recently purchased an OpenLog module and I'm experiencing the same issues.
